# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussdianpuxinxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('refid', models.IntegerField(null=True, verbose_name='关联表id')),
                ('userid', models.IntegerField(null=True, verbose_name='用户id')),
                ('nickname', models.CharField(max_length=100, null=True, verbose_name='用户名')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='评论内容')),
                ('reply', models.CharField(max_length=100, null=True, verbose_name='回复内容')),
            ],
            options={
                'db_table': 'discussdianpuxinxi',
            },
        ),
    ]
