# Generated by Django 4.0.5 on 2026-02-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField(verbose_name='用户ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(verbose_name='AI回答')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI聊天历史',
                'verbose_name_plural': 'AI聊天历史',
                'db_table': 'chat_history',
                'ordering': ['-addtime'],
            },
        ),
    ]
