# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('userid', models.IntegerField(verbose_name='用户id')),
                ('refid', models.IntegerField(verbose_name='收藏id')),
                ('tablename', models.CharField(max_length=200, verbose_name='表名')),
                ('name', models.CharField(max_length=200, verbose_name='收藏名称')),
                ('picture', models.CharField(max_length=200, verbose_name='收藏图片')),
                ('type', models.CharField(max_length=200, verbose_name='类型(1:收藏,21:赞,22:踩)')),
            ],
            options={
                'db_table': 'storeup',
            },
        ),
    ]
