# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('content', models.CharField(max_length=1000, verbose_name='帖子内容')),
                ('parentid', models.IntegerField(verbose_name='父节点id')),
                ('userid', models.IntegerField(verbose_name='用户id')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('isdone', models.CharField(max_length=200, verbose_name='状态')),
            ],
            options={
                'db_table': 'forum',
            },
        ),
    ]
