# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tablename', models.CharField(max_length=100, null=True, verbose_name='商品表名')),
                ('userid', models.IntegerField(null=True, verbose_name='用户id')),
                ('goodid', models.IntegerField(null=True, verbose_name='商品id')),
                ('goodname', models.CharField(max_length=100, null=True, verbose_name='商品名称')),
                ('picture', models.CharField(max_length=100, null=True, verbose_name='图片')),
                ('buynumber', models.IntegerField(null=True, verbose_name='购买数量')),
                ('price', models.FloatField(null=True, verbose_name='单价')),
                ('discountprice', models.FloatField(null=True, verbose_name='会员价')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
