# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jifenshangdian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('shangpinmingcheng', models.CharField(max_length=100, null=True, verbose_name='商品名称')),
                ('shangpintupian', models.CharField(max_length=100, null=True, verbose_name='商品图片')),
                ('shangpinjianjie', models.CharField(max_length=100, null=True, verbose_name='商品简介')),
                ('shangpinxiangqing', models.CharField(max_length=100, null=True, verbose_name='商品详情')),
                ('jifen', models.IntegerField(null=True, verbose_name='积分')),
            ],
            options={
                'db_table': 'jifenshangdian',
            },
        ),
    ]
