# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messagess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('userid', models.IntegerField(null=True, verbose_name='留言人id')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='用户名')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='留言内容')),
                ('cpicture', models.CharField(max_length=100, null=True, verbose_name='留言图片')),
                ('reply', models.CharField(max_length=100, null=True, verbose_name='回复内容')),
                ('rpicture', models.CharField(max_length=100, null=True, verbose_name='回复图片')),
            ],
            options={
                'db_table': 'messagess',
            },
        ),
    ]
