# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shangpinguanli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('shangpinmingcheng', models.CharField(max_length=100, null=True, verbose_name='商品名称')),
                ('shangpintupian', models.CharField(max_length=100, null=True, verbose_name='商品图片')),
                ('fenleimingcheng', models.CharField(max_length=100, null=True, verbose_name='分类名称')),
                ('jieshao', models.CharField(max_length=100, null=True, verbose_name='介绍')),
                ('xiangqing', models.CharField(max_length=100, null=True, verbose_name='详情')),
                ('dianpumingcheng', models.CharField(max_length=100, null=True, verbose_name='店铺名称')),
                ('userid', models.IntegerField(null=True, verbose_name='用户id')),
                ('price', models.FloatField(null=True, verbose_name='价格')),
                ('onelimittimes', models.IntegerField(null=True, verbose_name='单限')),
                ('alllimittimes', models.IntegerField(null=True, verbose_name='库存')),
                ('sfsh', models.CharField(max_length=100, null=True, verbose_name='是否审核')),
                ('shhf', models.CharField(max_length=100, null=True, verbose_name='审核回复')),
                ('thumbsupnum', models.IntegerField(null=True, verbose_name='赞')),
                ('crazilynum', models.IntegerField(null=True, verbose_name='踩')),
            ],
            options={
                'db_table': 'shangpinguanli',
            },
        ),
    ]
