# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shangjia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('yonghuming', models.CharField(max_length=100, null=True, verbose_name='用户名')),
                ('mima', models.CharField(max_length=100, null=True, verbose_name='密码')),
                ('shoujihao', models.CharField(max_length=100, null=True, verbose_name='手机号')),
                ('shangjiamingcheng', models.CharField(max_length=100, null=True, verbose_name='商家名称')),
                ('money', models.FloatField(null=True, verbose_name='余额')),
                ('jf', models.FloatField(null=True, verbose_name='积分')),
            ],
            options={
                'db_table': 'shangjia',
            },
        ),
    ]
