# Generated by Django 4.0.5 on 2026-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('type', models.IntegerField(default=1, verbose_name='类型')),
                ('condition_amount', models.FloatField(blank=True, null=True, verbose_name='满足金额')),
                ('discount_amount', models.FloatField(blank=True, null=True, verbose_name='减免金额')),
                ('total_count', models.IntegerField(verbose_name='发行总量')),
                ('receive_limit', models.IntegerField(default=1, verbose_name='每人限领')),
                ('valid_days', models.IntegerField(verbose_name='有效天数')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField(verbose_name='用户ID')),
                ('coupon_id', models.IntegerField(verbose_name='优惠券模板ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('condition_amount', models.FloatField(blank=True, null=True, verbose_name='满足金额')),
                ('discount_amount', models.FloatField(blank=True, null=True, verbose_name='减免金额')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('orderid', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单号')),
                ('receive_time', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('use_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'db_table': 'user_coupon',
            },
        ),
    ]
