# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='用户id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('tablename', models.CharField(blank=True, max_length=100, null=True, verbose_name='表名')),
                ('role', models.CharField(max_length=100, verbose_name='角色')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('expiratedtime', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
