# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='标题')),
                ('introduction', models.CharField(max_length=100, null=True, verbose_name='简介')),
                ('picture', models.CharField(max_length=100, null=True, verbose_name='系统公告图片')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='内容')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
