# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('refid', models.IntegerField(null=True, verbose_name='关联表id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='出入库物品名称')),
                ('sl', models.IntegerField(null=True, verbose_name='出入库数量')),
                ('crkzt', models.CharField(max_length=100, null=True, verbose_name='出入库状态')),
            ],
            options={
                'db_table': 'crk',
            },
        ),
    ]
