# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='管理员用户名')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='管理员密码')),
                ('role', models.CharField(default='管理员', max_length=100, null=True, verbose_name='角色')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
