# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shangpinfenlei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fenleimingcheng', models.CharField(max_length=100, null=True, verbose_name='分类名称')),
                ('fenleitupian', models.CharField(max_length=100, null=True, verbose_name='分类图片')),
            ],
            options={
                'db_table': 'shangpinfenlei',
            },
        ),
    ]
