# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.BigIntegerField(verbose_name='发送者Id')),
                ('sender_name', models.CharField(max_length=200, verbose_name='发送者昵称')),
                ('receiver', models.BigIntegerField(verbose_name='接受者id')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='接收者昵称')),
                ('msg', models.CharField(max_length=200, verbose_name='消息内容')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('read_status', models.IntegerField(verbose_name='是否已读')),
            ],
            options={
                'db_table': 'letter',
            },
        ),
    ]
