# Generated by Django 4.0.5 on 2026-02-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='receiver',
            field=models.BigIntegerField(verbose_name='接受者id'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender',
            field=models.BigIntegerField(verbose_name='发送者Id'),
        ),
    ]
