# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('userid', models.IntegerField(null=True, verbose_name='用户id')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='地址')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='收货人')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='电话')),
                ('isdefault', models.CharField(max_length=100, null=True, verbose_name='是否默认地址[是/否]')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
