# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('orderid', models.CharField(max_length=100, null=True, verbose_name='订单编号')),
                ('tablename', models.CharField(max_length=100, null=True, verbose_name='商品表名')),
                ('userid', models.IntegerField(null=True, verbose_name='用户id')),
                ('goodid', models.IntegerField(null=True, verbose_name='商品id')),
                ('goodname', models.CharField(max_length=100, null=True, verbose_name='商品名称')),
                ('picture', models.CharField(max_length=100, null=True, verbose_name='商品图片')),
                ('buynumber', models.IntegerField(null=True, verbose_name='购买数量')),
                ('price', models.FloatField(null=True, verbose_name='价格/积分')),
                ('discountprice', models.FloatField(null=True, verbose_name='折扣价格')),
                ('total', models.FloatField(null=True, verbose_name='总价格/总积分')),
                ('discounttotal', models.FloatField(null=True, verbose_name='折扣总价格')),
                ('type', models.IntegerField(null=True, verbose_name='支付类型')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='状态')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='地址')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
