# Generated by Django 4.0.5 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dianpuxinxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dianpumingcheng', models.CharField(max_length=100, null=True, verbose_name='店铺名称')),
                ('tupian', models.CharField(max_length=100, null=True, verbose_name='图片')),
                ('nicheng', models.CharField(max_length=100, null=True, verbose_name='昵称')),
                ('shangjiadianhua', models.CharField(max_length=100, null=True, verbose_name='商家电话')),
                ('dianpujianjie', models.CharField(max_length=100, null=True, verbose_name='店铺简介')),
                ('dianpudizhi', models.CharField(max_length=100, null=True, verbose_name='店铺地址')),
                ('userid', models.IntegerField(null=True, verbose_name='用户id')),
                ('lat', models.FloatField(null=True, verbose_name='lat')),
                ('lnt', models.FloatField(null=True, verbose_name='lnt')),
                ('conent', models.CharField(max_length=100, null=True, verbose_name='标记')),
                ('sfsh', models.CharField(max_length=100, null=True, verbose_name='是否审核')),
                ('shhf', models.CharField(max_length=100, null=True, verbose_name='审核回复')),
            ],
            options={
                'db_table': 'dianpuxinxi',
            },
        ),
    ]
